db_path: 'database.db'
base_weather_url: 'https://api.weather.gov/points/'
screen_size:
  height: 960
  width: 1600
resorts:
  killington:
    name: 'Killington'
    zip: '05751'
    latitude: '43.617'
    longitude: '-72.803'
    driving: True
    airport: RUT
    nonstop: 'True'
    stream: 'https://img.hdrelay.com/frames/a0de9878-d7b7-4906-9e83-536fde35c8a9/default/last.jpg'
  steamboat:
    name: 'Steamboat Springs'
    zip: '80487'
    latitude: '40.452'
    longitude: '-106.787'
    airport: HDN
    nonstop: ''
    stream: 'https://img.hdrelay.com/frames/e12dbfe2-9359-4b93-a8ce-b5e461b681d1/default/last.jpg'
  hood:
    name: 'Mt Hood Meadows'
    zip: '97041'
    latitude: '45.331'
    longitude: '-121.665'
    airport: PDX
    nonstop: 'True'
    stream: 'https://www.skihood.com/cams/vista'