db_path: 'database.db'
base_weather_url: 'https://api.weather.gov/points/'
screen_size:
  height: 480
  width: 800
resorts:
  steamboat:
    name: 'Steamboat Springs'
    latitude: '40.452'
    longitude: '-106.787'
    airport: HDN
    nonstop: ''
    stream: 'https://img.hdrelay.com/frames/e12dbfe2-9359-4b93-a8ce-b5e461b681d1/default/last.jpg'
  killington:
    name: 'Killington'
    latitude: '43.617'
    longitude: '-72.803'
    driving: True
    stream: 'https://img.hdrelay.com/frames/a0de9878-d7b7-4906-9e83-536fde35c8a9/default/last.jpg'
  hood:
    name: 'Mt Hood Meadows'
    latitude: '45.331'
    longitude: '-121.665'
    airport: PDX
    nonstop: 'True'
    stream: 'https://www.skihood.com/cams/vista'
  snowbird:
    name: 'Snowbird'
    latitude: '40.581'
    longitude: '-111.656'
    airport: SLC
    nonstop: 'True'
    stream: 'https://img.hdrelay.com/frames/8611e276-7ee5-42c0-b8cd-d9e1890e1cd4/default/last.jpg'
  stratton:
    name: 'Stratton'
    latitude: '43.113'
    longitude: '-72.908'
    driving: 'True'
    stream: 'https://img.youtube.com/vi/3B_ODJiExKU/maxresdefault.jpg'
  parkcity:
    name: 'Park City'
    latitude: '40.651'
    longitude: '-111.508'
    airport: SLC
    nonstop: 'True'
    stream: 'https://b7.hdrelay.com/camera/d4d8b786-d517-4069-bb09-ccc679b553a5/snapshot'
  attitash:
    name: 'Attitash Mountain'
    latitude: '44.082'
    longitude: '-71.229'
    driving: 'True'
    stream: 'https://live2.brownrice.com/cam-images/attitash2.jpg'